In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("H:/Decision Minds/folder1/FINALDATASETCopy.CSV")
dataset

AccountNumber                                        AccountName  \
0      ACCT0000005                                   WagerWorks, Inc.   
1      ACCT0000006                                           OUHSC IT   
2      ACCT0000011                               Allstate Corporation   
3      ACCT0000026                                Clark County Nevada   
4      ACCT0000029  AAA Northern California, Nevada & Utah Insuran...   
...            ...                                                ...   
3552   ACCT0078498                               Fujitsu - PersoPoint   
3553   ACCT0079312                                Westfield Labs Corp   
3554   ACCT0079408                                           IBM IS&T   
3555   ACCT0080144                       Fujitsu - Frontoffice Center   
3556   ACCT0080598                         FX Innovation - Jean Coutu   

      CompleteCustomerChurn  CustomerAgeCategoryIndicator  \
0                         1                      1.000000   
1                         0                      1.000000   
2                         0                      0.666667   
3                         0                      1.000000   
4                         0                      0.666667   
...                     ...                           ...   
3552                      0                      0.000000   
3553                      0                      0.000000   
3554                      0                      0.000000   
3555                      0                      0.000000   
3556                      0                      0.000000   

      AcctPaymentStatusIndicator  RepChangesinLast002Months_SUM  \
0                              1                            0.2   
1                              1                            0.4   
2                              1                            0.0   
3                              1                            0.2   
4                              1                            0.2   
...                          ...                            ...   
3552                           1                            0.2   
3553                           1                            0.0   
3554                           1                            0.0   
3555                           1                            0.0   
3556                           1                            0.0   

      NumberOfProductionInstances_SUM  OptyWonLast12Months_Percent_SUM  \
0                              0.0000                           0.0000   
1                              0.2857                           0.5000   
2                              0.0000                           0.2222   
3                              0.0000                           0.6666   
4                              0.0000                           1.0000   
...                               ...                              ...   
3552                           0.0000                           1.0000   
3553                           0.0000                           1.0000   
3554                           0.0000                           1.0000   
3555                           0.0000                           1.0000   
3556                           0.0000                           1.0000   

      OverallEngagementSatisfactionIndicator_SUM  \
0                                            0.5   
1                                            0.0   
2                                            0.0   
3                                            0.0   
4                                            0.0   
...                                          ...   
3552                                         0.0   
3553                                         0.0   
3554                                         0.0   
3555                                         0.0   
3556                                         0.0   

      FulfillerPriceCategoryIndicator  KnowledgeEventAttendeeCount  \
0     

In [3]:
import numpy as np
import statsmodels.formula.api as sm
logit_model = sm.logit('CompleteCustomerChurn~CustomerAgeCategoryIndicator+AcctPaymentStatusIndicator+RepChangesinLast002Months_SUM+NumberOfProductionInstances_SUM+OptyWonLast12Months_Percent_SUM+OverallEngagementSatisfactionIndicator_SUM+FulfillerPriceCategoryIndicator+KnowledgeEventAttendeeCount+TotalAdoptionPercent+LicensedAdoptionPercent+AdoptionCategoryIndicator+LicensingCategoryIndicator+ResponseRatePercent+NPSSatisfactionIndicator_SUM+OverallSupportSurveySatisfactionIndicator_SUM+UsageRiskIndicator_SUM+TotalActivityCount_SUM',data = dataset).fit()

         Current function value: 0.089876
         Iterations: 35


c:\users\kumar ambuj\appdata\local\programs\python\python37-32\lib\site-packages\statsmodels\base\model.py:512: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


In [4]:
print(logit_model.summary())

                             Logit Regression Results                            
Dep. Variable:     CompleteCustomerChurn   No. Observations:                 3557
Model:                             Logit   Df Residuals:                     3539
Method:                              MLE   Df Model:                           17
Date:                   Tue, 17 Dec 2019   Pseudo R-squ.:                  0.5638
Time:                           13:22:56   Log-Likelihood:                -319.69
converged:                         False   LL-Null:                       -732.82
Covariance Type:               nonrobust   LLR p-value:                1.152e-164
                                                    coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------------
Intercept                                         9.8586      1.444      6.829      0.000       7.029      12.688
Cu

In [5]:
logit_model.pred_table()

array([[3340.,   30.],
       [  86.,  101.]])

In [6]:
accuracy=(3341+101)/(3341+30+86+101)
accuracy

0.9673974142776841

In [7]:
#dropping feature RepChangesinLast002Months_SUM 

In [8]:
logit_model = sm.logit('CompleteCustomerChurn~CustomerAgeCategoryIndicator+AcctPaymentStatusIndicator+NumberOfProductionInstances_SUM+OptyWonLast12Months_Percent_SUM+OverallEngagementSatisfactionIndicator_SUM+FulfillerPriceCategoryIndicator+KnowledgeEventAttendeeCount+TotalAdoptionPercent+LicensedAdoptionPercent+AdoptionCategoryIndicator+LicensingCategoryIndicator+ResponseRatePercent+NPSSatisfactionIndicator_SUM+OverallSupportSurveySatisfactionIndicator_SUM+UsageRiskIndicator_SUM+TotalActivityCount_SUM',data = dataset).fit()

         Current function value: 0.090189
         Iterations: 35


c:\users\kumar ambuj\appdata\local\programs\python\python37-32\lib\site-packages\statsmodels\base\model.py:512: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


In [9]:
print(logit_model.summary())

                             Logit Regression Results                            
Dep. Variable:     CompleteCustomerChurn   No. Observations:                 3557
Model:                             Logit   Df Residuals:                     3540
Method:                              MLE   Df Model:                           16
Date:                   Tue, 17 Dec 2019   Pseudo R-squ.:                  0.5622
Time:                           13:22:57   Log-Likelihood:                -320.80
converged:                         False   LL-Null:                       -732.82
Covariance Type:               nonrobust   LLR p-value:                4.718e-165
                                                    coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------------
Intercept                                        10.0932      1.420      7.106      0.000       7.309      12.877
Cu

In [10]:
logit_model.pred_table()

array([[3339.,   31.],
       [  82.,  105.]])

In [11]:
accuracy=(3340+105)/(3340+31+82+105)
accuracy

0.9682405845980888

In [12]:
# dropping feature NumberOfProductionInstances_SUM

In [13]:
logit_model = sm.logit('CompleteCustomerChurn~CustomerAgeCategoryIndicator+AcctPaymentStatusIndicator+OptyWonLast12Months_Percent_SUM+OverallEngagementSatisfactionIndicator_SUM+FulfillerPriceCategoryIndicator+KnowledgeEventAttendeeCount+TotalAdoptionPercent+LicensedAdoptionPercent+AdoptionCategoryIndicator+LicensingCategoryIndicator+ResponseRatePercent+NPSSatisfactionIndicator_SUM+OverallSupportSurveySatisfactionIndicator_SUM+UsageRiskIndicator_SUM+TotalActivityCount_SUM',data = dataset).fit()

Optimization terminated successfully.
         Current function value: 0.091061
         Iterations 12


In [14]:
print(logit_model.summary())

                             Logit Regression Results                            
Dep. Variable:     CompleteCustomerChurn   No. Observations:                 3557
Model:                             Logit   Df Residuals:                     3541
Method:                              MLE   Df Model:                           15
Date:                   Tue, 17 Dec 2019   Pseudo R-squ.:                  0.5580
Time:                           13:22:59   Log-Likelihood:                -323.90
converged:                          True   LL-Null:                       -732.82
Covariance Type:               nonrobust   LLR p-value:                1.323e-164
                                                    coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------------
Intercept                                        10.2806      1.424      7.222      0.000       7.491      13.071
Cu

In [15]:
logit_model.pred_table()

array([[3339.,   31.],
       [  82.,  105.]])

In [16]:
accuracy=(3340+105)/(3340+31+82+105)
accuracy

0.9682405845980888

In [17]:
# dropping feature FulfillerPriceCategoryIndicator

In [18]:
logit_model = sm.logit('CompleteCustomerChurn~CustomerAgeCategoryIndicator+AcctPaymentStatusIndicator+OptyWonLast12Months_Percent_SUM+OverallEngagementSatisfactionIndicator_SUM+KnowledgeEventAttendeeCount+TotalAdoptionPercent+LicensedAdoptionPercent+AdoptionCategoryIndicator+LicensingCategoryIndicator+ResponseRatePercent+NPSSatisfactionIndicator_SUM+OverallSupportSurveySatisfactionIndicator_SUM+UsageRiskIndicator_SUM+TotalActivityCount_SUM',data = dataset).fit()

Optimization terminated successfully.
         Current function value: 0.091177
         Iterations 12


In [19]:
print(logit_model.summary())

                             Logit Regression Results                            
Dep. Variable:     CompleteCustomerChurn   No. Observations:                 3557
Model:                             Logit   Df Residuals:                     3542
Method:                              MLE   Df Model:                           14
Date:                   Tue, 17 Dec 2019   Pseudo R-squ.:                  0.5574
Time:                           13:22:59   Log-Likelihood:                -324.32
converged:                          True   LL-Null:                       -732.82
Covariance Type:               nonrobust   LLR p-value:                2.550e-165
                                                    coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------------
Intercept                                        10.1244      1.408      7.190      0.000       7.364      12.884
Cu

In [20]:
logit_model.pred_table()

array([[3339.,   31.],
       [  83.,  104.]])

In [21]:
accuracy=(3340+104)/(3340+31+83+104)
accuracy

0.9679595278246206

In [22]:
# dropping feature LicensedAdoptionPercent

In [23]:
logit_model = sm.logit('CompleteCustomerChurn~CustomerAgeCategoryIndicator+AcctPaymentStatusIndicator+OptyWonLast12Months_Percent_SUM+OverallEngagementSatisfactionIndicator_SUM+KnowledgeEventAttendeeCount+TotalAdoptionPercent+AdoptionCategoryIndicator+LicensingCategoryIndicator+ResponseRatePercent+NPSSatisfactionIndicator_SUM+OverallSupportSurveySatisfactionIndicator_SUM+UsageRiskIndicator_SUM+TotalActivityCount_SUM',data = dataset).fit()

Optimization terminated successfully.
         Current function value: 0.091249
         Iterations 12


In [24]:
logit_model.pred_table()

array([[3340.,   30.],
       [  83.,  104.]])

In [25]:
accuracy=(3341+104)/(3341+30+83+104)
accuracy

0.9682405845980888

In [26]:
print(logit_model.summary())

                             Logit Regression Results                            
Dep. Variable:     CompleteCustomerChurn   No. Observations:                 3557
Model:                             Logit   Df Residuals:                     3543
Method:                              MLE   Df Model:                           13
Date:                   Tue, 17 Dec 2019   Pseudo R-squ.:                  0.5571
Time:                           13:23:01   Log-Likelihood:                -324.57
converged:                          True   LL-Null:                       -732.82
Covariance Type:               nonrobust   LLR p-value:                4.067e-166
                                                    coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------------
Intercept                                        10.1414      1.408      7.205      0.000       7.383      12.900
Cu

In [27]:
#dropping feature ResponseRatePercent

In [28]:
logit_model = sm.logit('CompleteCustomerChurn~CustomerAgeCategoryIndicator+AcctPaymentStatusIndicator+OptyWonLast12Months_Percent_SUM+OverallEngagementSatisfactionIndicator_SUM+KnowledgeEventAttendeeCount+TotalAdoptionPercent+AdoptionCategoryIndicator+LicensingCategoryIndicator+NPSSatisfactionIndicator_SUM+OverallSupportSurveySatisfactionIndicator_SUM+UsageRiskIndicator_SUM+TotalActivityCount_SUM',data = dataset).fit()

Optimization terminated successfully.
         Current function value: 0.091598
         Iterations 12


In [29]:
logit_model.pred_table()

array([[3338.,   32.],
       [  83.,  104.]])

In [30]:
accuracy=(3339+104)/(3339+32+83+104)
accuracy

0.9676784710511523

In [31]:
print(logit_model.summary())

                             Logit Regression Results                            
Dep. Variable:     CompleteCustomerChurn   No. Observations:                 3557
Model:                             Logit   Df Residuals:                     3544
Method:                              MLE   Df Model:                           12
Date:                   Tue, 17 Dec 2019   Pseudo R-squ.:                  0.5554
Time:                           13:23:01   Log-Likelihood:                -325.82
converged:                          True   LL-Null:                       -732.82
Covariance Type:               nonrobust   LLR p-value:                1.643e-166
                                                    coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------------
Intercept                                         9.9763      1.394      7.157      0.000       7.244      12.708
Cu

In [32]:
# dropping feature UsageRiskIndicator_SUM

In [33]:
logit_model = sm.logit('CompleteCustomerChurn~CustomerAgeCategoryIndicator+AcctPaymentStatusIndicator+OptyWonLast12Months_Percent_SUM+OverallEngagementSatisfactionIndicator_SUM+KnowledgeEventAttendeeCount+TotalAdoptionPercent+AdoptionCategoryIndicator+LicensingCategoryIndicator+NPSSatisfactionIndicator_SUM+OverallSupportSurveySatisfactionIndicator_SUM+TotalActivityCount_SUM',data = dataset).fit()

Optimization terminated successfully.
         Current function value: 0.091884
         Iterations 12


In [34]:
logit_model.pred_table()

array([[3340.,   30.],
       [  82.,  105.]])

In [35]:
accuracy=(3342+105)/(3342+105+82+29)
accuracy

0.9688026981450253

In [36]:
print(logit_model.summary())

                             Logit Regression Results                            
Dep. Variable:     CompleteCustomerChurn   No. Observations:                 3557
Model:                             Logit   Df Residuals:                     3545
Method:                              MLE   Df Model:                           11
Date:                   Tue, 17 Dec 2019   Pseudo R-squ.:                  0.5540
Time:                           13:23:02   Log-Likelihood:                -326.83
converged:                          True   LL-Null:                       -732.82
Covariance Type:               nonrobust   LLR p-value:                5.092e-167
                                                    coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------------
Intercept                                         9.8023      1.353      7.242      0.000       7.150      12.455
Cu

In [37]:
#dropping feature TotalActivityCount_SUM 

In [38]:
logit_model = sm.logit('CompleteCustomerChurn~CustomerAgeCategoryIndicator+AcctPaymentStatusIndicator+OptyWonLast12Months_Percent_SUM+OverallEngagementSatisfactionIndicator_SUM+KnowledgeEventAttendeeCount+TotalAdoptionPercent+AdoptionCategoryIndicator+LicensingCategoryIndicator+NPSSatisfactionIndicator_SUM+OverallSupportSurveySatisfactionIndicator_SUM',data = dataset).fit()

Optimization terminated successfully.
         Current function value: 0.092024
         Iterations 11


In [39]:
logit_model.pred_table()

array([[3341.,   29.],
       [  81.,  106.]])

In [40]:
accuracy=(3342+106)/(3342+106+29+81)
accuracy

0.9690837549184935

In [41]:
print(logit_model.summary())

                             Logit Regression Results                            
Dep. Variable:     CompleteCustomerChurn   No. Observations:                 3557
Model:                             Logit   Df Residuals:                     3546
Method:                              MLE   Df Model:                           10
Date:                   Tue, 17 Dec 2019   Pseudo R-squ.:                  0.5533
Time:                           13:23:03   Log-Likelihood:                -327.33
converged:                          True   LL-Null:                       -732.82
Covariance Type:               nonrobust   LLR p-value:                9.027e-168
                                                    coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------------
Intercept                                         9.7893      1.352      7.240      0.000       7.139      12.439
Cu